name: crenno_study_case
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  # STATE MANAGEMENT
  flutter_bloc: ^9.1.1
  # NETWORK
  dio: ^5.9.2
  # ROUTE
  go_router: ^17.2.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
